/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:a7a8611b-62d4-4200-96a6-e3700693ffbe",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_8BRVh9igb",
    "aws_user_pools_web_client_id": "8tvluu3pn49p1cfd46jfk16fm",
    "oauth": {}
};


export default awsmobile;
